(function($j){$j.EndecaSearchSuggestor=function(ele,opts){this._active=true;this._options=opts;this._lastValue="";this._element=ele;
this._container=$j('<div class="aheadSearch"></>');this._timeOutId=this._options.timeOutId;this._contextPath=this._options.contextPath;
this._hideTimeOutId;this._selectedIndex=-1;this._selectedID="";var suggestor=this;$j("body").append(this._container);ele.keydown(function(e){switch(e.keyCode){case 38:if(suggestor._active){suggestor.moveToPrev();
}else{suggestor.show();}break;case 40:if(suggestor._active){suggestor.moveToNext();}else{suggestor.show();}break;case 9:suggestor.hide();
break;case 13:if(suggestor._active&&suggestor._selectedIndex!=-1){e.preventDefault();suggestor.selectItem();return false;
}break;case 27:if(suggestor._active){suggestor.hide();}break;}});ele.keydown(_.debounce(function(e){var keyCode=e.keyCode;
if(keyCode!==38&&keyCode!==40&&keyCode!==9&&keyCode!==13&&keyCode!==27){suggestor.handleRequest();}},150));};$j.EndecaSearchSuggestor.prototype.moveToPrev=function(){if(this._selectedIndex==-1){this._selectedIndex=0;
}else{if(this._selectedIndex==0){return;}this._selectedIndex--;}$j(".dimResult",this._container).removeClass("active");obj=$j($j(".dimResult",this._container).get(this._selectedIndex));
$j(obj).addClass("active");};$j.EndecaSearchSuggestor.prototype.moveToNext=function(){if(this._selectedIndex==-1){this._selectedIndex=0;
}else{if(this._selectedIndex==$j(".dimResult",this._container).length-1){return;}this._selectedIndex++;}$j(".dimResult",this._container).removeClass("active");
obj=$j($j(".dimResult",this._container).get(this._selectedIndex));$j(obj).addClass("active");$j(obj).trigger("mouseover");
};$j.EndecaSearchSuggestor.prototype.selectItem=function(text,position,url){var itemTerm=text;var itemPosition=parseInt(position);
var itemUrl=url;var itemKeyword=$j.trim(this._element.val());var itemList="typeahead";if(!itemTerm){var selectedItem=$j(".dimResult",this._container).get(this._selectedIndex);
itemTerm=$(selectedItem).text();itemPosition=this._selectedIndex+1;itemUrl=$(selectedItem).attr("href");}if(typeof dataLayer!="undefined"){dataLayer.push({event:"e_searchAutoCompleteClick",searchAutoComplete:{keyword:itemKeyword,term:itemTerm,list:itemList,position:itemPosition,description:itemTerm}});
}document.location.href=itemUrl;};$j.EndecaSearchSuggestor.prototype.hide=function(){this._container.hide();$j(".typeahead__overlay").hide();
this._active=false;};$j.EndecaSearchSuggestor.prototype.hideRightBlock=function(){$j(".typeahead__right-block").hide();};
$j.EndecaSearchSuggestor.prototype.showRightBlock=function(){if(!heb.screen.isSmall){$j(".typeahead__right-block").show();
}this._active=true;};$j.EndecaSearchSuggestor.prototype.show=function(){if(this._container.is(":hidden")){this.setPosition();
this._container.show();this._active=true;this._selectedIndex=-1;$("body").click(function(e){if(!$(e.target).closest(".aheadSearch").length){$(".aheadSearch").hide();
$j(".typeahead__overlay").hide();}});}};$j.EndecaSearchSuggestor.prototype.handleRequest=function(){var suggestor=this;var defaultSearchText="Search products, recipes, and more";
var text=$j.trim(suggestor._element.val());if(""!==text&&defaultSearchText!==text&&text!==suggestor._lastValue&&text.length>0){suggestor.requestData();
}if(text===""&&suggestor._lastValue!==""){suggestor.hide();}suggestor._lastValue=text;};$j.EndecaSearchSuggestor.prototype.requestData=function(){var suggestor=this;
var response=$j.ajaxQueue({url:suggestor.composeUrl(),dataType:"html",async:true,success:function(data){suggestor.showSearchResult(data);
}});};$j.EndecaSearchSuggestor.prototype.composeUrl=function(){var url=this._options.autoSuggestServiceUrl;var searchTerm=$j.trim(this._element.val());
if(url.indexOf("?")==-1){url+="?";}else{url+="&";}url+="q="+searchTerm;return url;};$j.EndecaSearchSuggestor.prototype.showSearchResult=function(data){if(data!=undefined&&data!=null&&data!=""){this._container.html(data);
this.bindEventHandler();this.show();$j(".typeahead__overlay").show();}else{this.hide();}};$j.EndecaSearchSuggestor.prototype.bindEventHandler=function(){var suggestor=this;
$j("div.aheadSearch a.dimResult").mouseover(function(e){var text=$("a",this).text();var lastSel=$j(".dimResult.active",suggestor._container).attr("id");
$j(".dimResult.active",suggestor._container).removeClass("active");$j(this).addClass("active");});$j("a",$j("li.dimResult",this._container)).click(function(e){e.preventDefault();
var text=$(this).text();var position=$(this).parent().attr("id");var url=$(this).attr("href");suggestor.selectItem(text,position,url);
return false;});$j(".dimRoots",this._container).click(function(){clearTimeout(suggestor._hideTimeOutId);suggestor._element.focus();
});$j("div.aheadSearch li.dimResult a").mouseover(function(e){e.preventDefault();e.stopPropagation();});};$j.EndecaSearchSuggestor.prototype.generateRightBlock=function(text){console.log("text : "+text);
var link=this._contextPath+"/search/includes/typeaheadmouseover.jsp?searchTerm="+text;$.get(link,function(data){$("#rightContainer").html(data);
},"html");};$j.EndecaSearchSuggestor.prototype.setPosition=function(){const isMobile=window.heb.screen.isSmall;const offset=this._element.offset();
this._container.css({top:offset.top+this._element.outerHeight(),left:isMobile?"0px":offset.left,minWidth:this._element.outerWidth()+"px",width:isMobile?"100%":undefined});
};$j.fn.endecaSearchSuggest=function(options){var opts=$j.extend({},$j.fn.endecaSearchSuggest.defaults,options);this.each(function(){var element=$j(this);
new $j.EndecaSearchSuggestor(element,opts);});};$j.fn.endecaSearchSuggest.defaults={minAutoSuggestInputLength:2,displayImage:false,delay:250,autoSuggestServiceUrl:"",collection:"",searchUrl:"",containerClass:"dimSearchSuggContainer",defaultImage:"no_image.gif"};
})(jQuery);