$(document).ready(function(){$("body").on("click","#main-nav a",function(a){var b=[];target=$(a.target);parent=target.closest("ul").closest("li");grandParent=parent.closest("ul").closest("li");grandParent.children("a").length&&b.push(grandParent.children("a").text());parent.children("a").length?b.push(parent.children("a").text()):parent.children("span").length&&b.push(parent.children("span").text());b.push(a.target.innerText);a="";for(i=0;i<b.length;i++)a+=b[i].trim(),i<b.length-1&&(a+=">");gtm_e_menuNav("main",
a)});$("body").on("click","#menuNav a",function(a){var b=[];target=$(a.target);parent=target.closest("ul").closest("li");grandParent=parent.closest("ul").closest("li");grandParent.children("a").length&&b.push(grandParent.children("a").text());parent.children("a").length?b.push(parent.children("a").text()):parent.children("span").length&&b.push(parent.children("span").text());b.push(a.target.innerText);a="";for(i=0;i<b.length;i++)a+=b[i].trim(),i<b.length-1&&(a+=">");gtm_e_menuNav("main",a)});$("body").on("click",
"#footer a",function(a){var b=[];target=$(a.target);header=target.closest("ul").prev("h4");header.length&&b.push(header.text());b.push(target.text());a="";for(i=0;i<b.length;i++)a+=b[i].trim(),i<b.length-1&&(a+=">");gtm_e_menuNav("footer",a)});$("#prodSortBySelect").on("change",function(){gtm_e_sortApplied(this.options[this.selectedIndex].text)})});
function gtmOnClickHandler(a,b){"undefined"!=typeof dataLayer&&(console.debug("e_filterApplied:"+a+": "+b),dataLayer.push({event:"e_filterApplied",filterApplied:{type:a,value:b}}))}function gtm_e_menuNav(a,b){"undefined"!=typeof dataLayer&&(console.debug("gtm_e_menuNav:"+a+": "+b),dataLayer.push({event:"e_menuNav",menuType:a,menuItemText:b}))}function gtm_e_sortApplied(a){"undefined"!=typeof dataLayer&&(console.debug("gtm_e_sortApplied:"+a),dataLayer.push({event:"e_sortApplied",sortApplied:a}))}
function gtm_e_selectCoupon(a,b,c,d){"undefined"!=typeof dataLayer&&(console.debug("gtm_e_selectCoupon:"+a+":"+b+":"+c+":"+d),dataLayer.push({event:"e_selectCoupon",coupon:{title:b,id:a,position:d,type:c}}))}
function gtm_e_searchAutoCompleteClick(a,b,c,d){if("undefined"!=typeof dataLayer){var e=$("#searchText").val(),f=$(".dimResult.active").text();console.debug("gtm_e_searchAutoCompleteClick:"+a+":"+e+":"+f+":"+b+":"+c+":"+d);dataLayer.push({event:"e_searchAutoCompleteClick",searchAutoComplete:{id:a,keyword:e,term:f,list:b,position:c,description:d}})}}
function gtm_e_addToCart(a,b,c){"undefined"!=typeof dataLayer&&(a=$(a).next('script[type="application/ld+json"]').text(),a=JSON.parse(a),"undefined"!=typeof a?("undefined"!=typeof b&&(a.ecommerce.add.products[0].quantity=b),"undefined"!=typeof c&&(b=$(c+" :selected").text().trim(),"$"==b.charAt(0)&&(b=b.substr(1),b=parseFloat(b)),a.ecommerce.add.products[0].price=b),dataLayer.push(a)):console.warn("GTM-addToCart was not able to push to dataLayer"))}
function gtm_e_addToCart_onUpdate(a,b,c){b<c&&gtm_e_addToCart(a,c)}
function gtm_e_addToList(a,b,c){if("undefined"!=typeof dataLayer){b=$("#gtm-add-to-list-product-"+a).text();a:{try{JSON.parse(b)}catch(e){var d=!1;break a}d=!0}d?(b=JSON.parse(b),"undefined"!=typeof c&&(c=$(c+" :selected").text().trim(),"$"==c.charAt(0)&&(c=c.substr(1),c=parseFloat(c)),b.ecommerce.add.products[0].price=c),b.forEach(function(b){("e_productClick"!==b.event||thisProductHasntAlreadyBeenClicked(a))&&dataLayer.push(b)}),VueStore.$store.commit("profile/PUSH_CLICKED_PRODUCT_ID",a)):console.warn("GTM-addToList was not able to push to dataLayer")}}
function gtm_e_loginPasswordReset(){"undefined"!=typeof dataLayer&&dataLayer.push({event:"e_loginPasswordReset"})}function gtm_e_login(){"undefined"!=typeof dataLayer&&dataLayer.push({event:"e_login"})}function gtm_e_productClick(a){var b=a.replace("gtm-product-click-","");"undefined"!=typeof dataLayer&&thisProductHasntAlreadyBeenClicked(b)&&(a=document.getElementById(a),a=JSON.parse(a.text),dataLayer.push(a),VueStore.$store.commit("profile/PUSH_CLICKED_PRODUCT_ID",b))}
function thisProductHasntAlreadyBeenClicked(a){return-1===VueStore.$store.state.profile.gtmClickedProductIds.indexOf(a)}function gtm_e_addAllToCart(a){"undefined"!=typeof dataLayer&&dataLayer.push(a)};