version: '3'
services:
  web:
    container_name: nginx2
    ports: 
      - "8081:80"
    volumes:
      - "/home/user/docker-images/my-docker-compose/html:/usr/share/nginx/html"
    image: nginx
    networks:
      - net-test
  web2:
    container_name: nginx3
    ports: 
      - "8082:80"
    image: httpd
    networks:
      - net-test
networks:
  net-test: